pipeline{
	agent any
	
	stages{
		stage('Checkout'){
			steps{
				git credentialsId: '', url: ''
			}
		}
    		stage('Setup'){
      			steps{
				sh 'echo \'test phase\''
      			}
    		}
    		stage('Test'){
      			steps{
				 sh 'echo \'test phase\''
               }
   		}
		stage('invoke playbook'){
      			steps{
				
      			}
   		}
	}
}